version: 2.0

jobs:
  product:
    machine: true
    steps:
      - checkout
      - run: chmod 777 ./.circleci/build_and_deploy.sh
      - run: bash ./.circleci/build_and_deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - product:
        context: GCP
        filters:
          branches:
            only: master
